export const LOGIN_BY_PASS = {
  REQUEST: 'LOGIN_BY_PASS_REQUEST',
  RECEIVE: 'LOGIN_BY_PASS_RECEIVE',
  FAILURE: 'LOGIN_BY_PASS_FAILURE',
}

export const LOGOUT = {
  REQUEST: 'LOGOUT_REQUEST',
  RECEIVE: 'LOGOUT_RECEIVE',
  FAILURE: 'LOGOUT_FAILURE',
}
